# Generated by Django 2.1.7 on 2020-04-21 22:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_frames', models.IntegerField(choices=[(6, 6), (12, 12), (18, 18)], default=12, null=True, verbose_name='Number of Frames')),
                ('delay', models.IntegerField(choices=[(4, '25 fps'), (8, '12 fps'), (16, '6 fps')], default=6, null=True, verbose_name='Animation Speed')),
                ('method', models.CharField(choices=[('hue_rotate', 'Hue Rotate'), ('replace_color', 'Replace Color')], default='hue_rotate', max_length=16)),
                ('negate_channel', models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=8, null=True)),
                ('replace_color', models.CharField(blank=True, max_length=32, null=True)),
                ('fuzz', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49)], default=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('src', models.ImageField(upload_to='source_images')),
                ('colors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('n_frames', models.IntegerField(default=0)),
                ('visibility', models.CharField(choices=[('needs_review', 'needs_review'), ('private', 'private'), ('public', 'public'), ('hidden', 'hidden')], default='unknown', max_length=16)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='partyimage',
            name='sourceimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.SourceImage'),
        ),
    ]
