# Generated by Django 2.1.7 on 2020-04-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyimage',
            name='delay',
        ),
        migrations.AddField(
            model_name='partyimage',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to='.party'),
        ),
    ]
