# Generated by Django 2.2.12 on 2020-04-23 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_sourceimage_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partyimage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sourceimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourceimage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='partyimage',
            name='n_frames',
            field=models.IntegerField(choices=[(7, 7), (12, 12), (18, 18)], default=7, null=True, verbose_name='Number of Frames'),
        ),
        migrations.AlterField(
            model_name='sourceimage',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='sourceimage',
            name='visibility',
            field=models.CharField(choices=[('needs_review', 'needs_review'), ('private', 'private'), ('public', 'public'), ('hidden', 'hidden'), ('trash', 'trash')], default='needs_review', max_length=16),
        ),
    ]
