# Generated by Django 2.1.7 on 2019-04-05 03:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceimage',
            name='colors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sourceimage',
            name='n_frames',
            field=models.IntegerField(default=0),
        ),
    ]
