# Generated by Django 2.1.7 on 2019-04-05 19:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190405_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceimage',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='sourceimage',
            name='colors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sourceimage',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
