# Generated by Django 2.1.7 on 2020-04-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190405_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resize', models.IntegerField(choices=[(0, 'No Resize'), (32, 32), (64, 64), (128, 128), (256, 256)], verbose_name='Resize Image')),
                ('n_frames', models.IntegerField(choices=[(6, 6), (8, 8), (10, 10), (12, 12), (16, 16), (20, 20), (24, 24), (30, 30), (32, 32)], default=12, null=True, verbose_name='Number of Frames')),
                ('delay', models.IntegerField(choices=[(2, '50 fps'), (4, '25 fps'), (6, '16 fps'), (8, '12 fps'), (10, '10 fps'), (12, '8 fps'), (16, '6 fps'), (20, '5 fps')], default=6, null=True, verbose_name='Animation Speed')),
                ('method', models.CharField(choices=[('hue_rotate', 'Hue Rotate'), ('replace_color', 'Replace Color')], default='rotate', max_length=16)),
                ('negate', models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=8, null=True, verbose_name='Negate Channel')),
                ('replace_color', models.CharField(blank=True, max_length=32, null=True)),
                ('fuzz', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49)], default=3, null=True)),
                ('sourceimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.SourceImage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
