# Generated by Django 2.1.7 on 2020-04-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_partyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceimage',
            name='visibility',
            field=models.CharField(choices=[('needs_review', 'needs_review'), ('private', 'private'), ('public', 'public'), ('hidden', 'hidden')], default='unknown', max_length=16),
        ),
    ]
